'use client';

import { useState } from 'react';
import { ArrowUpRight, ArrowDown, Menu, X, Star, Compass, Code2, Mail, Crosshair } from 'lucide-react';
import data from '@/data/portfolio.json';

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [category, setCategory] = useState('All');
  const skills = data.skills.filter(s => category === 'All' || s.category === category);
  return <div id="home" className="frontier">
    <header className="masthead"><a className="brand" href="#home">PP<span>★</span></a><nav aria-label="Main navigation" className={menuOpen ? 'navigation open' : 'navigation'}>{[['The story','about'],['Selected work','work'],['The arsenal','skills']].map(([label,id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav><a className="header-cta" href="#contact">LET’S TALK <ArrowUpRight size={15}/></a><button className="menu-toggle" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X/> : <Menu/>}</button></header>
    <main id="main">
      <section className="hero"><div className="hero-art" role="img" aria-label="Western outlaw and horseback riders against a crimson frontier sunset"/><div className="hero-content"><div className="eyebrow"><span/> INDEPENDENT DEVELOPER. UNTAMED CURIOSITY.</div><h1>PRAVEEN<br/>PRASAD</h1><div className="hero-rule"/><h2>GOOD CODE.<br/>NO SHORTCUTS.</h2><p>Full-stack developer out of Kerala, India.<br/>Building dependable digital experiences<br/>for people with a little ambition.</p><a href="#work" className="button">RIDE THROUGH MY WORK <ArrowUpRight size={17}/></a></div><div className="hero-side">A DEVELOPER’S TALE — EST. 2023</div><div className="hero-bottom"><span><i/> AVAILABLE FOR THE NEXT CHAPTER</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={14}/></a><span>11.05° N &nbsp; 76.07° E</span></div></section>
      <div className="manifesto"><span>DESIGN WITH INTENT.</span><Star/><span>BUILD WITH GRIT.</span><Star/><span>LEAVE A MARK.</span></div>
      <section id="work" className="section work"><div className="section-heading"><div><div className="eyebrow">CHAPTER I / PROOF OF WORK</div><h2>A FEW <span>GOOD BUILDS.</span></h2></div><p>Every project has a story.<br/>These are a few worth telling.</p></div><div className="projects">{data.projects.map((p,i) => <a href={p.link} target="_blank" rel="noreferrer" key={p.id} className="wanted"><div className="poster-top"><span>SELECTED WORK</span><span>NO. 00{i+1}</span></div><h3>{['BUILT TO SELL','BUILT TO TEACH','BUILT TO CONNECT'][i]}</h3><div className={`project-illustration scene-${i}`}><span className="poster-sun"/><div className="mountains"/><div className="project-emblem">{i === 0 ? <Star/> : i === 1 ? <Code2/> : <Compass/>}</div><span className="poster-caption">{['COMMERCE & POSSIBILITY','KNOWLEDGE WITHOUT LIMITS','OPPORTUNITY BEYOND BORDERS'][i]}</span></div><div className="poster-body"><h4>{p.title}</h4><p>{p.description}</p><div className="tags">{p.technologies.slice(0,3).map(t => <span key={t}>{t}</span>)}</div><div className="poster-link">EXPLORE THE PROJECT <ArrowUpRight size={17}/></div></div></a>)}</div><div className="work-footnote"><span>BUILT WITH PURPOSE. SHIPPED WITH PRIDE.</span><span>★ ★ ★</span></div></section>
      <section id="about" className="section story"><div className="story-title"><div className="eyebrow">CHAPTER II / THE MAN BEHIND THE WORK</div><h2>A BUILDER.<br/>A THINKER.<br/><span>STILL RIDING.</span></h2><div className="story-stamp"><Star/><span>BASED IN KERALA<br/><b>BUILDING EVERYWHERE</b></span></div></div><div className="story-copy"><p className="lead">The best work comes from curiosity, a steady hand, and seeing things through.</p><p>{data.about.bio}</p><p>I learn by doing. Pick up a new tool, ask the difficult question, and stay with the problem until the pieces fit. That’s how I approach every project and every team.</p><a className="text-link" href={data.about.socials[0].url} target="_blank" rel="noreferrer">MORE OF MY STORY <ArrowUpRight size={16}/></a><div className="experience">{data.experiences.map(e => <article key={e.id}><span className="timeline-dot"/><small>{e.period}</small><h3>{e.title}</h3><p>{e.company}</p><p>{e.description}</p></article>)}</div></div></section>
      <section id="skills" className="section arsenal"><div className="section-heading"><div><div className="eyebrow">CHAPTER III / TOOLS OF THE TRADE</div><h2>THE <span>ARSENAL.</span></h2></div><p>Well-chosen tools. Well-earned experience.<br/>Everything the next job calls for.</p></div><div className="filters" aria-label="Filter skills">{['All','Frontend','Backend','Tools'].map(c => <button key={c} className={category === c ? 'active' : ''} aria-pressed={category === c} onClick={() => setCategory(c)}>{c === 'All' ? 'ALL EQUIPMENT' : c.toUpperCase()}</button>)}<span>{skills.length} IN THE KIT</span></div><div className="skill-grid">{skills.map((s,i) => <div className="skill" key={s.id}><span className="skill-index">{String(i+1).padStart(2,'0')}</span><h3>{s.name}</h3><small>{s.category}</small><Crosshair size={17}/></div>)}</div></section>
      <section className="section services"><div className="section-heading"><div><div className="eyebrow">CHAPTER IV / WHAT I BRING TO THE TABLE</div><h2>CONSIDER IT <span>HANDLED.</span></h2></div></div><div className="service-grid">{data.services.map((s,i) => <details key={s.id}><summary><span>0{i+1}</span><h3>{s.title}</h3><b>+</b></summary><p>{s.description}</p></details>)}</div></section>
      <section id="contact" className="section contact"><div className="eyebrow">THERE’S ALWAYS ANOTHER GOOD STORY.</div><h2>LET’S MAKE<br/><span>THE NEXT ONE.</span></h2><p>Got an idea worth chasing? I’m all ears.</p><a className="button light" href={`mailto:${data.about.email}`}>SEND A MESSAGE <Mail size={16}/></a><a className="email" href={`mailto:${data.about.email}`}>{data.about.email}</a><Star className="contact-star"/></section>
    </main><footer><a className="brand" href="#home">PP<span>★</span></a><span>© {new Date().getFullYear()} PRAVEEN PRASAD</span><div>{data.about.socials.map(s => <a key={s.id} href={s.url} target="_blank" rel="noreferrer">{s.platform}<ArrowUpRight size={12}/></a>)}</div><a className="back-top" href="#home">BACK TO TOP ↑</a><p>Red Dead Redemption 2-inspired personal portfolio. Not affiliated with Rockstar Games.</p></footer>
  </div>;
}

